### ISSUE TITLE
Trouble installing the entourage dependency

### ISSUE THREAD

**Issue by dymayday** [Moonsong-Labs/hackathon-agents#1]
I have trouble installing the entourage dependency in `pyproject.toml`. 

```toml
[tool.uv.sources]
entourage-utils = { git = "https://github.com/Moonsong-Labs/entourage.git", subdirectory = "entourage-utils", rev = "hackathon-template" }
```

1. https auth does not seem to work for me on Mac, I'm using ssh usually. This https way is not prompting for creds as it should I guess and just fails.
Here is the log : 
```bash
   Updating https://github.com/Moonsong-Labs/entourage.git (hackathon-template)                                                                                     × Failed to download and build `entourage-utils @ git+https://github.com/Moonsong-Labs/entourage.git@hackathon-template#subdirectory=entourage-utils`
  ├─▶ Git operation failed
  ├─▶ failed to fetch into: /Users/meidhy/.cache/uv/git-v0/db/2de1eb5135ca0ade
  ├─▶ failed to fetch branch or tag `hackathon-template`
  ╰─▶ process didn't exit successfully: `/opt/homebrew/bin/git fetch --force --update-head-ok 'https://github.com/Moonsong-Labs/entourage.git'
      '+refs/tags/hackathon-template:refs/remotes/origin/tags/hackathon-template'` (exit status: 128)
      --- stderr
      fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

2. There is no `hackathon-template` branch in the entourage repo.
